name: build-main-self-hosted

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  build-main-self-hosted:
    runs-on: [self-hosted, linux, ARM64]
    container: ubuntu:20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ""

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y universe

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Run vcs export
        run: |
          vcs export --exact src || true

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro galactic

      - name: Build CARET
        run: |
          wget https://github.com/tier4/caret/archive/refs/heads/galactic.zip
          unzip galactic.zip
          mv caret-galactic ~/ros2_caret_ws
          cd ~/ros2_caret_ws
          mkdir src
          vcs import src < caret.repos
          ./setup_caret.sh -c
          . /opt/ros/galactic/setup.sh
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          . /opt/ros/galactic/setup.sh
          . ~/ros2_caret_ws/install/local_setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF

      - name: Verify build
        run: |
          . /opt/ros/galactic/setup.sh
          . ~/ros2_caret_ws/install/local_setup.sh
          ros2 caret check_caret_rclcpp --workspace ./
